{
 "title": "中电科信物联网平台",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "温度",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "agriculture_metrics{metric=\"temperature\",location=\"雄安\"}",
     "legendFormat": "雄安养殖基地"
    },
    {
     "expr": "agriculture_metrics{metric=\"temperature\",location=\"万全\"}",
     "legendFormat": "万全种植基地"
    },
    {
     "expr": "agriculture_metrics{metric=\"temperature\",location=\"官厅湖\"}",
     "legendFormat": "官厅湖"
    }
   ]
  },
  {
   "title": "PM2.5",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "agriculture_metrics{metric=\"pm2.5\",location=\"雄安\"}",
     "legendFormat": "雄安养殖基地"
    },
    {
     "expr": "agriculture_metrics{metric=\"pm2.5\",location=\"万全\"}",
     "legendFormat": "万全种植基地"
    },
    {
     "expr": "agriculture_metrics{metric=\"pm2.5\",location=\"官厅湖\"}",
     "legendFormat": "官厅湖"
    }
   ]
  },
  { "title": "报警", "type": "alertlist", "gridPos": { "h": 18, "w": 6, "x": 18, "y": 0 } },
  {
   "title": "湿度",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "agriculture_metrics{metric=\"humidity\",location=\"雄安\"}",
     "legendFormat": "雄安养殖基地"
    },
    {
     "expr": "agriculture_metrics{metric=\"humidity\",location=\"万全\"}",
     "legendFormat": "万全种植基地"
    },
    {
     "expr": "agriculture_metrics{metric=\"humidity\",location=\"官厅湖\"}",
     "legendFormat": "官厅湖"
    }
   ]
  },
  {
   "title": "大气压力",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 9 },
   "yaxes": [
    { "format": "pressurekpa" }
   ],
   "targets": [
    {
     "expr": "agriculture_metrics{metric=\"atmosPressure\",location=\"雄安\"}",
     "legendFormat": "雄安养殖基地"
    },
    {
     "expr": "agriculture_metrics{metric=\"atmosPressure\",location=\"万全\"}",
     "legendFormat": "万全种植基地"
    },
    {
     "expr": "agriculture_metrics{metric=\"atmosPressure\",location=\"官厅湖\"}",
     "legendFormat": "官厅湖"
    }
   ]
  }
 ]
}