#!/bin/bash

#for mac

version=1.0

if [ $# -gt 1 ]; then
  echo "Usage: $0 [service]"
  echo "  service: prom/grafana/doppler/client/server, server means prom + grafana + doppler. Default is blank, meaning start them all."
  exit 0
fi

if [ $# = 0 ]; then
  grafana=true
  prom=true
  doppler=true
  client=true
fi

arg=ops

if [ "$1" = "server" ]; then
  grafana=true
  prom=true
  doppler=true
fi

if [ "$1" = "grafana" ]; then
  grafana=true
fi

if [ "$1" = "prom" ]; then
  prom=true
fi

if [ "$1" = "doppler" ]; then
  doppler=true
fi

if [ "$1" = "client" ]; then
  client=true
fi

if [ $grafana ]; then
  echo -e
  echo "#### starting grafana ####"
  image=frankhang/grafana:$version
  docker run --name grafana -d -p 3300:3300 -v ~/grafanadata:/var/lib/grafana $image
fi

if [ $prom ]; then
  echo -e
  echo "#### starting prom ####"
  image=frankhang/prom-$arg:$version
  docker run --name prom -d -p 8090:8090 -v ~/promdata:/etc/prometheus/data $image
# docker run --name prom -d -p 8090:8090 $image

fi


if [ $doppler ]; then
  echo -e
  echo "#### starting doppler ####"
  image=frankhang/doppler:$version
  docker run --name doppler -d -p 8125:8125/udp -p 8825:8825 $image -L=debug
fi

if [ $client ]; then
  echo -e
  echo "#### starting client  ####"
  image=frankhang/client:$version
  docker run --name client -d $image -url=host.docker.internal:8125
fi
