#!/bin/bash

#for mac

version=1.0

if [ $# -gt 1 ]; then
  echo "Usage: $0 [service]"
  echo "  service: prom/grafana/doppler/client/server, server means prom + grafana + doppler. Default is blank, meaning start them all."
  exit 0
fi

if [ $# = 0 ]; then
  grafana=true
  prom=true
  doppler=true
  telegraf=true
  agent=true
  client=true
fi

arg=ops

if [ "$1" = "server" ]; then
  grafana=true
  prom=true
  doppler=true
  telegraf=true
fi

if [ "$1" = "grafana" ]; then
  grafana=true
fi

if [ "$1" = "prom" ]; then
  prom=true
fi

if [ "$1" = "doppler" ]; then
  doppler=true
fi

if [ "$1" = "telegraf" ]; then
  telegraf=true
fi

if [ "$1" = "agent" ]; then
  agent=true
fi

if [ "$1" = "client" ]; then
  client=true
fi

if [ "$1" = "tele" ]; then
  telegraf=true
  agent=true
fi

if [ $grafana ]; then
  echo -e
  echo "#### starting grafana ####"
  image=frankhang/grafana:$version
  docker stop grafana
  docker rm grafana
  docker run --name grafana -d -p 3300:3300 -v ~/grafanadata:/var/lib/grafana $image
fi

if [ $prom ]; then
  echo -e
  echo "#### starting prom ####"
  image=frankhang/prom-$arg:$version
  docker stop prom
  docker rm prom
  docker run --name prom -d -p 8090:8090 -v ~/promdata:/etc/prometheus/data $image
# docker run --name prom -d -p 8090:8090 $image

fi

if [ $doppler ]; then
  echo -e
  echo "#### starting doppler ####"
  image=frankhang/doppler:$version
  docker stop doppler
  docker rm doppler
  docker run --name doppler -d -p 8125:8125/udp -p 8825:8825 $image -L=debug
fi

if [ $telegraf ]; then
  echo -e
  echo "#### starting telegraf ####"
  image=frankhang/telegraf:$version
  docker stop telegraf
  docker rm telegraf
  docker run --name telegraf -d -p 8094:8094 -p 8894:8894 $image
fi

if [ $agent ]; then
  echo -e
  echo "#### starting agent ####"
  image=frankhang/agent:$version
  docker stop agent
  docker rm agent
  docker run --name agent -d $image
fi

if [ $client ]; then
  echo -e
  echo "#### starting client  ####"
  image=frankhang/client:$version
  docker stop client1
  docker rm client1
  docker stop client2
  docker rm client2
  docker run --name client1 -d $image -url=host.docker.internal:8125
  docker run --name client2 -d $image -url=host.docker.internal:8125
fi
