#!/bin/bash

#for mac

if [ $# = 0 ]; then
    server=true
    client=true
fi

if [ "$1" = "server"  ]; then
    server=true

fi

if [ "$1" = "client"  ]; then
    client=true
fi


if [ $server ]; then
  docker run --name prom --rm -d -p 9090:9090 frankhang/prom-ops:1.0
  docker run --name grafana --rm -d -p 4000:4000 frankhang/grafana:1.0
  docker run --name doppler --rm -d -p 8125:8125/udp -p 8825:8825 frankhang/doppler:1.0 -L=debug
fi

if [ $client ]; then
  docker run --name client  --rm -d frankhang/client:1.0 -url=host.docker.internal:8125
fi
