host = "0.0.0.0"
port = 8125
token-limit = 1000
read-timeout = 15
write-timeout = 15
Test = "t2"

#log_payloads = true

[log]
level = "debug"

    #file log related config.
    [log.file]

    #Log filename, leave empty to disable file log.
    filename = "doppler.log"

    #Max size for a single file, in MB and cannot be large than 4096MB.
    max-size = 10

    #Max log keep days, default is never deleting.
    max-days = 10

    #Maximum number of old log files to retain.
    max-backups = 90